openapi: 3.0.1
info:
  title: API administrador de tareas
  description: Esta API se encarga de administrar una serie de tareas.
  version: 1.0.0
servers:
  - url: http://localhost:3000/
tags:
  - name: tareas
    description: En este endpoint se manejan todas las tareas.

paths:
  /:
    post:
      tags:
        - tareas
      summary: Insertar una tarea en la BD.
      parameters:
        - $ref: '#/components/parameters/token'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BodyTareasPost'
      responses:
        200:
          description: (OK) Tarea guardada exitosamente.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExitoTareasPost'
        400:
          $ref: '#/components/responses/BadRequest'
        401:
          $ref: '#/components/responses/Unauthorized'
        404:
          $ref: '#/components/responses/NotFound'
        500:
          $ref: '#/components/responses/ServerError'

  /{idTareas}:
    get:
      tags:
        - tareas
      summary: Obtiene información de una tarea de la base de datos.
      parameters:
        - $ref: '#/components/parameters/token'
        - name: idTareas
          in: path
          description: Identificador de la tarea a obtener.
          required: true
          schema:
            type: string
      responses:
        200:
          description: (OK) Se obtuvo la información de la tarea.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExitoTareasGet'
        400:
          $ref: '#/components/responses/BadRequest'
        401:
          $ref: '#/components/responses/Unauthorized'
        404:
          $ref: '#/components/responses/NotFound'
        500:
          $ref: '#/components/responses/ServerError'

    delete:
      tags:
        - tareas
      summary: Elimina una tarea de la base de datos.
      parameters:
        - $ref: '#/components/parameters/token'
        - name: idTareas
          in: path
          description: Identificador de la tarea a eliminar.
          required: true
          schema:
            type: string
      responses:
        200:
          description: (OK) Tarea eliminada exitosamente.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExitoTareasDelete'
        400:
          $ref: '#/components/responses/BadRequest'
        401:
          $ref: '#/components/responses/Unauthorized'
        404:
          $ref: '#/components/responses/NotFound'
        500:
          $ref: '#/components/responses/ServerError'

components:
  responses:
    Unauthorized:
      description: (Unauthorized) No hay autorización para llamar al servidor.
    NotFound:
      description: (NotFound) No se encontró la información.
    BadRequest:
      description: (BadRequest) Los datos enviados son incorrectos o hay datos obligatorios no enviados.
    ServerError:
      description: Error en el servidor.

  parameters:
    token:
      name: token  
      in: header
      description: Token de autorización.
      required: true
      schema:
        type: string

  schemas:
    BodyTareasPost:
      type: object
      properties:
        title:
          type: string
        description:
          type: string

    ExitoTareasPost:
      type: object
      properties:
        respuesta:
          type: integer
          enum: [1]
          description: Bandera que indica si la llamada al servicio fue exitosa.

    ExitoTareasGet:
      type: object
      properties:
        title:
          type: string
        description:
          type: string

    ExitoTareasDelete:
      type: object
      properties:
        respuesta:
          type: integer
          enum: [1]
          description: Bandera que indica si la eliminación fue exitosa.
